// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "github.com/jscastelblancoh/statistic_service/statistic/pkg/endpoint"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeGetHandler(m, endpoints, options["Get"])
	makeGetbyIdHandler(m, endpoints, options["GetbyId"])
	makePutHandler(m, endpoints, options["Put"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	makePostHandler(m, endpoints, options["Post"])
	return m
}
